[CE-192] Add aditional check to set_post_contents
the-events-calendar/WP-Router pull request #1
Opened 2023-08-17 17:30 UTC by redscar

When using themes like Divi the content is being outputted multiple times. However, WP_Router does not take into account if it's a WP_Router page. This change adds an extra check to make sure that it only replaces WP_Router content.

2023-08-23 17:36 UTC, codingmusician approved these changes

2023-08-29 01:38 UTC, bordoni requested changes

2023-08-29 01:38 UTC, bordoni commented on WP_Router_Page.class.php
> +        }
Invert conditional, and use `[]` for the array definition.

2023-08-30 14:01 UTC, juanfra reviewed
Looking good. Left a couple of comments, all nits

2023-08-30 14:01 UTC, juanfra commented on WP_Router_Page.class.php
> +     * @param object $post
Is it a `WP_Post` object? A clarification of the type of object and its structure in the docblock could be helpful.

2023-08-30 14:01 UTC, juanfra commented on WP_Router_Page.class.php
> +        if ( WP_Router_Page::POST_TYPE == $post->post_type ) {
Should we have a strict comparison?

Also, we tend apply the logic of "bailing early" in our codebase. Maybe we can invert the conditional and return. And if not, execute the code.

2023-08-30 14:01 UTC, juanfra commented on readme.txt
> +* Fix - Added an additional check for `set_post_contents` so that it only runs on posts that are created via WP-Router.
Would it be worth it to start including the ticket ID in the readme entries, maybe it could help to track things down in the future.

2023-08-30 14:07 UTC, codingmusician commented on WP_Router_Page.class.php
> +    }
```suggestion
    public function set_post_contents( $post ) {
        if ( WP_Router_Page::POST_TYPE !== $post->post_type ) {
            return;
        }
        global $pages;
        $pages = [ $this->contents ];
    }
```

2023-08-30 14:44 UTC, juanfra approved these changes
LGTM

2023-08-30 14:51 UTC, merged